== Context

The system is designed to check is a phrase contains profanity. A message passed as a `text` parameter to `http://localhost:8080/checkprofanity` gets checked and appropriate result is provided to the client.

If the `text` contains swear words - they get maked and a masked message is returned.


== How to run

. Run `mvn clean install -DskipTests` in parent's POM
** Skip tests, because we don't want to run the tests at first. We want to build / release the contract artifact and prepare the stubs
** Within the install process the `Spring Cloud Contract Verifier` will
*** generate and run tests (for provider)
*** produce and install stubs (for consumer)
** As we focus on stubs at first - we skip the tests
** The log line confirms successful creation of stubs
+
----
[INFO] Installing /some/path/http-server/target/http-server-0.0.1-SNAPSHOT-stubs.jar to /path/to/your/.m2/repository/com/example/http-server/0.0.1-SNAPSHOT/http-server-0.0.1-SNAPSHOT-stubs.jar
----

. Separate tests can be run on both consumer and provider side
. Consumer uses the stub to run the tests
** Consumer uses wiremock to validate if the client implementations works
+
----
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment=WebEnvironment.NONE)
@AutoConfigureStubRunner(ids = {"com.example:http-server-dsl:+:stubs:6565"}, workOffline = true)
public class ClientServiceTests {
  // ...
}
----
** Validation is based on the stubs generated by the provider (who owns the stubs)

. Provider generated the stubs and validates client's expectations with it's own tests

== Task #{counter:cdc}

Implement the _client's_ `IsSwearWord WebClient.check(String input)` method do that when client tests are triggered (`mvn clean test`) is suggessfully passes

== Task #{counter:cdc}

Implement _provider's_ response so that it satisfies the contract

== Task #{counter:cdc}

A new expectations (from a new client) is designed in a form of contract (`/contracts/contracts/history.groovy`) - create appropriate provider endpoints so that the contracts get satisfied.

TIP: use `RecordDao` class to get all historical records from the `profanity-check-service`
